sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t9Vw8XHz1SU2wmGie1Y
    access-key-secret: 4ust0cwI7En7evBdgD4pNXY6YwXgI9
    bucket-name: hzg-sky
